spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
      username: root
      password: root
      platform: postgresql
    jpa:
      generate-ddl: true
      hibernate:
        use-new-id-generator-mappings: true
